version: "3.4"

services:
  web:
    build:
      context: .
      target: devel
      args:
      - USERUID
      - USERGID
    env_file:
    - .env
    ports:
    - $PORT:$PORT
    volumes:
    - .:/work:Z
    command: sleep infinity  # needed for VSCode/RemoteContainer
