# Generated by Django 2.2.12 on 2020-11-25 17:17

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsession',
            name='ai_class',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
